version: '3.4'

services:
  webhookapi:
    image: ${DOCKER_REGISTRY}webhookapi
    build:
      context: .
      dockerfile: WebhookAPI/Dockerfile

  webportal:
    image: ${DOCKER_REGISTRY}webportal
    build:
      context: .
      dockerfile: WebPortal/Dockerfile

