// <auto-generated />
using System;
using Gitloy.Services.WebhookAPI.BusinessLogic.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gitloy.Services.WebhookAPI.Migrations
{
    [DbContext(typeof(WebhookApiContext))]
    [Migration("20181011092227_AddCreateAtAttributeToModels")]
    partial class AddCreateAtAttributeToModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gitloy.Services.WebhookAPI.BusinessLogic.Core.Model.Integration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("DeleteFlag");

                    b.Property<string>("FtpHostname")
                        .IsRequired();

                    b.Property<string>("FtpPassword")
                        .IsRequired();

                    b.Property<int>("FtpPort");

                    b.Property<string>("FtpRootDirectory");

                    b.Property<string>("FtpUsername");

                    b.Property<string>("GitBranch");

                    b.Property<string>("GitUrl")
                        .IsRequired();

                    b.Property<Guid>("Guid");

                    b.HasKey("Id");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("Gitloy.Services.WebhookAPI.BusinessLogic.Core.Model.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("DeleteFlag");

                    b.Property<Guid>("Guid");

                    b.Property<int?>("IntegrationId");

                    b.Property<string>("ResultDetails");

                    b.Property<string>("ResultMessage");

                    b.Property<int>("ResultStatus");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Gitloy.Services.WebhookAPI.BusinessLogic.Core.Model.Request", b =>
                {
                    b.HasOne("Gitloy.Services.WebhookAPI.BusinessLogic.Core.Model.Integration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId");
                });
#pragma warning restore 612, 618
        }
    }
}
